imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: images.yml }

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

framework:
    esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'], assets_version: 1.0 }
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ MopaBootstrapBundle, NinjaLunchBundle, FOSCommentBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %env.bin.node%
            node_paths: %env.path.node_modules%
            apply_to: "\.less$"
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ninja\Lunch\LunchBundle\Entity\User


mopa_bootstrap:
    navbar: ~
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default

knp_gaufrette:
    adapters:
        profile_images:
            local:
                directory: %kernel.root_dir%/../web/uploads/profile-images/
                create: true

    filesystems:
        profile_images_fs:
            adapter:    profile_images

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        profile_image:
            uri_prefix: /uploads/profile-images
            upload_destination: profile_images_fs
            delete_on_remove: true # determines whether to delete file upon removal of entity
            inject_on_load: false # determines whether to inject a File instance upon load


fos_comment:
    db_driver: orm
    class:
        model:
            comment: Ninja\Lunch\LunchBundle\Entity\Comment
            thread: Ninja\Lunch\LunchBundle\Entity\Comment\Thread

fos_rest:
    view:
        mime_types: {modal: ['text/html'], widget: ['text/html'], html: ['text/html']}
        templating_formats:
            widget: true
            modal: true
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    format_listener:
        prefer_extension: true
