<?php

namespace Ninja\Lunch\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoodOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodOrderRepository extends EntityRepository
{
    /**
     *
     * Hide's the logic for what to do when no current order exists
     *
     * @return FoodOrder The FoodOrder for today
     */
    public function getCurrent() {
        $qb = $this->createQueryBuilder('fo');

        $qb
            ->andWhere($qb->expr()->eq('fo.date', ':today'))
            ->setParameters(array(
                'today' => new \DateTime('12am')
            ))
        ;

        $order = $qb->getQuery()->getOneOrNullResult();

        if($order === null){
             $order = new FoodOrder();
             $em    = $this->getEntityManager();
             $em->persist($order);
             $em->flush();
        }

        return $order;
    }
}
