<?php

namespace Ninja\Lunch\LunchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoodItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodItemRepository extends EntityRepository
{
}
